fix35

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,13 +41,14 @@ jobs:
 
       - name: ✅ Lint style (Norminette)
         run: |
-            files=$(find . -type f -name '*.c' ! -path './tests/*')
-            output=$(norminette -R CheckForbiddenSourceHeader $files)
-            echo "$output"
-            errors=$(echo "$output" | grep -v 'Error: INVALID_HEADER' | grep 'Error:')
-            if [ -n "$errors" ]; then
-              echo "Erreur(s) autre(s) que INVALID_HEADER détectée(s) :"
-              echo "$errors"
-              exit 1
-            fi
+              files=$(find . -type f -name '*.c' ! -path './tests/*')
+              output=$(norminette -R CheckForbiddenSourceHeader $files 2>&1)
+              echo "$output"
+              errors=$(echo "$output" | grep -v 'Error: INVALID_HEADER' | grep 'Error:')
+              if [ -n "$errors" ]; then
+                echo "Erreur(s) autre(s) que INVALID_HEADER détectée(s) :"
+                echo "$errors"
+                exit 1
+              fi
+
 
